schema_version: 1

context:
  name: lsstdesc-crow
  version: "1.0.8"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lsstdesc_crow-${{ version }}.tar.gz
  sha256: 6333d5f0db554b2a3c7affd2429ee44b11087be3fac637e96068f202b4f654c2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - clmm
    - numpy >=2.0
    - pyccl >=2.8.0
    - scipy >=1.12
  run_constraints:
    - numcosmo >=0.21.1
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - crow
      pip_check: true

about:
  homepage: https://github.com/LSSTDESC/crow
  summary: Cluster Reconstruction of Observables Workbench
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eduardojsbarroso
    - caioolivv
